stages:
  - unit-test
  - integration-test
  - qedcore-integration-test
  - verify-unit-test-deps

.untit_test_template:
  stage: unit-test
  variables:
      CI_QED_TEST_TYPE: "unit"
      CI_QED_DISABLE_LONG_TESTS: "ON"
  script:
    # test CI scripts
    - cd ${CI_PROJECT_DIR}/.ci/CI/
    - julia --project=. -e 'import Pkg; Pkg.instantiate()'
    - julia --project=. -e 'import Pkg; Pkg.test(; coverage = true)'
    - cd ${CI_PROJECT_DIR}
    # test QuantumElectrodynamics.jl
    - $(julia --project=${CI_PROJECT_DIR}/.ci/CI/ ${CI_PROJECT_DIR}/.ci/CI/script/get_project_name_version_path.jl ${CI_PROJECT_DIR})
    - echo "CI_QED_DEV_PKG_NAME -> $CI_QED_DEV_PKG_NAME"
    - echo "CI_QED_DEV_PKG_VERSION -> $CI_QED_DEV_PKG_VERSION"
    - echo "CI_QED_DEV_PKG_PATH -> $CI_QED_DEV_PKG_PATH"
    - julia --project=${CI_PROJECT_DIR}/.ci/CI -e 'import Pkg; Pkg.test(; coverage = true)'
    - julia --project=${CI_PROJECT_DIR}/.ci/CI ${CI_PROJECT_DIR}/.ci/CI/script/setup_dev_env.jl ${CI_PROJECT_DIR}
    - julia --project=. -e 'import Pkg; Pkg.instantiate()'
    - julia --project=. -e 'import Pkg; Pkg.test(; coverage = true)'
  interruptible: true
  tags:
    - cpuonly
    - x86_64

unit_tests_releases:
  extends: .untit_test_template
  parallel:
    matrix:
      - JULIA_VERSION: ["1.10", "1.11", "1.12", "rc"]
  image: julia:$JULIA_VERSION

unit_tests_nightly:
  extends: .untit_test_template
  # use the same baseimage like the official julia images
  image: debian:bookworm-slim
  variables:
    # path where julia tar bal should be downloaded
    JULIA_DONWLOAD: /julia/download
    # path where julia should be extracted
    JULIA_EXTRACT: /julia/extract
  before_script:
    - apt update && apt install -y wget
    - mkdir -p $JULIA_DONWLOAD
    - mkdir -p $JULIA_EXTRACT
    - >
      if [[ $CI_RUNNER_EXECUTABLE_ARCH == "linux/arm64" ]]; then
        wget https://julialangnightlies-s3.julialang.org/bin/linux/aarch64/julia-latest-linux-aarch64.tar.gz -O $JULIA_DONWLOAD/julia-nightly.tar.gz
      elif [[ $CI_RUNNER_EXECUTABLE_ARCH == "linux/amd64" ]]; then
        wget https://julialangnightlies-s3.julialang.org/bin/linux/x86_64/julia-latest-linux-x86_64.tar.gz -O $JULIA_DONWLOAD/julia-nightly.tar.gz
      else
        echo "unknown runner architecture -> $CI_RUNNER_EXECUTABLE_ARCH"
        exit 1
      fi
    - tar -xf $JULIA_DONWLOAD/julia-nightly.tar.gz -C $JULIA_EXTRACT
    # we need to search for the julia base folder name, because the second part of the name is the git commit hash
    # e.g. julia-b0c6781676f
    - JULIA_EXTRACT_FOLDER=${JULIA_EXTRACT}/$(ls $JULIA_EXTRACT | grep -m1 julia)
    # copy everything to /usr to make julia public available
    # mv is not possible, because it cannot merge folder
    - cp -r $JULIA_EXTRACT_FOLDER/* /usr
  allow_failure: true
  tags:
    - cpuonly
    - x86_64

verify-unit-test-deps:
  image: julia:1.10
  stage: verify-unit-test-deps
  script:
    - >
      if [[ $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_REF_NAME == "main" || $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_REF_NAME == "dev" ]]; then
        # does not check for custom package URLs on the main and dev branch
        echo "no custom package URL check necessary"
      else
        julia --project=${CI_PROJECT_DIR}/.ci/CI/ -e 'import Pkg; Pkg.instantiate()'
        julia --project=${CI_PROJECT_DIR}/.ci/CI/ ${CI_PROJECT_DIR}/.ci/CI/script/verify_env.jl
      fi
  interruptible: true
  tags:
    - cpuonly
    - x86_64

bootloader_jl_integration_test:
  image: julia:1.10
  stage: integration-test
  variables:
    CI_QED_DISABLE_SHORT_TESTS: "ON"
  script:
    - cd ${CI_PROJECT_DIR}/.ci/CI/
    - julia --project=. -e 'import Pkg; Pkg.instantiate()'
    - julia --project=. -e 'import Pkg; Pkg.test()'
  interruptible: true
  tags:
    - cpuonly
    - x86_64

get_gitlab_ci_conf_jl_integration_test:
  image: julia:1.10
  stage: integration-test
  script:
    - apt update && apt install -y git
    - cd ${CI_PROJECT_DIR}/.ci/CI/
    - julia --project=. -e 'import Pkg; Pkg.instantiate()'
    - $(julia --project=. ${CI_PROJECT_DIR}/.ci/CI/script/get_gitlab_ci_conf.jl)
    - env | grep CI_QED_
  interruptible: true
  tags:
    - cpuonly
    - x86_64

trigger_job:
  stage: qedcore-integration-test
  variables:
    # use bootloader.jl code of the pull request
    CI_QED_GIT_CI_TOOLS_URL: "${CI_PROJECT_URL}.git"
    CI_QED_GIT_CI_TOOLS_BRANCH: $CI_COMMIT_REF_NAME
    # need to enable generating test jobs for a pull request by hand because pipeline is triggered
    # by other project and not a pull request (automatic detection mechanism does not work)
    # use CI_QED_IS_PR instead CI_QED_ENABLE_INTEG_TESTS to simulate behavior of pull request
    CI_QED_IS_PR: "ON"
  trigger:
    project: hzdr/qedjl-project/qedcore.jl
    strategy: depend
  # run only in pull requests
  rules:
    - if: $CI_COMMIT_REF_NAME =~ /^pr-*./
